# Generated by Django 6.0.2 on 2026-03-08 22:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('iata_code', models.CharField(max_length=3, unique=True)),
                ('icao_code', models.CharField(blank=True, max_length=4, null=True)),
                ('airport_type', models.CharField(choices=[('large_airport', 'Large Airport'), ('medium_airport', 'Medium Airport')], max_length=20)),
                ('city', models.CharField(blank=True, default='', max_length=255)),
                ('country', models.CharField(help_text='ISO country code', max_length=10)),
                ('continent', models.CharField(blank=True, default='', max_length=2)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
