# Generated by Django 6.0.2 on 2026-04-26 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0001_initial'),
        ('people', '0004_alter_person_phone_number'),
        ('stations', '0003_alter_station_station_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='preferred_airport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_by_people', to='airports.airport'),
        ),
        migrations.AddField(
            model_name='person',
            name='preferred_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_by_people', to='stations.station'),
        ),
    ]
