# Generated by Django 6.0.2 on 2026-04-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_tripstop_person_alter_tripstop_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('BOOKED', 'Booked'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
    ]
