# Generated by Django 6.0.2 on 2026-04-26 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0001_initial'),
        ('people', '0005_person_preferred_airport_person_preferred_station'),
        ('stations', '0003_alter_station_station_type'),
        ('trips', '0003_trip_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripstop',
            name='person',
        ),
        migrations.AddField(
            model_name='tripstop',
            name='airport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='airports.airport'),
        ),
        migrations.AddField(
            model_name='tripstop',
            name='people',
            field=models.ManyToManyField(blank=True, to='people.person'),
        ),
        migrations.AddField(
            model_name='tripstop',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stations.station'),
        ),
    ]
