# Generated by Django 6.0.2 on 2026-04-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_remove_tripstop_person_tripstop_airport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripstop',
            name='snapshot_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='tripstop',
            name='snapshot_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
