# Generated by Django 6.0.2 on 2026-04-29 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_tripstop_snapshot_address_tripstop_snapshot_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TripLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('transport_type', models.CharField(choices=[('FLIGHT', 'Flight'), ('TRAIN', 'Train'), ('BUS', 'Bus'), ('CAR', 'Car')], default='CAR', max_length=20)),
                ('booking_reference', models.CharField(blank=True, max_length=100)),
                ('ticket_data', models.JSONField(blank=True, default=dict)),
                ('arrival_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_legs', to='trips.tripstop')),
                ('departure_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_legs', to='trips.tripstop')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='trips.trip')),
            ],
        ),
    ]
